# Generated by Django 6.0.6 on 2026-06-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
    ]
